apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  labels:
    app: aggregator-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: aggregator-service
  type: LoadBalancer
