apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
spec:
  selector:
    matchLabels:
      app: aggregator-service
  replicas: 1
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
      - name: aggregator-service
        image: 871154751090.dkr.ecr.eu-west-2.amazonaws.com/aggregator-service:latest
        ports:
        - containerPort: 80
